import { normalizeDestinationText } from './destination-photos';

const IATA_BY_CITY: Record<string, string> = {
  'abu dhabi': 'AUH',
  'acapulco': 'ACA',
  'ama': 'AMM',
  'amsterda': 'AMS',
  'aracaju': 'AJU',
  'aruba': 'AUA',
  'assuncao': 'ASU',
  'atenas': 'ATH',
  'atlanta': 'ATL',
  'auckland': 'AKL',
  'bangkok': 'BKK',
  'barcelona': 'BCN',
  'bariloche': 'BRC',
  'beirute': 'BEY',
  'belem': 'BEL',
  'belgrado': 'BEG',
  'belo horizonte': 'PLU',
  'bergen': 'BGO',
  'berlim': 'TXL',
  'boa vista': 'BVB',
  'bogota': 'BOG',
  'bolonha': 'BLQ',
  'boston': 'BOS',
  'brasilia': 'BSB',
  'brisbane': 'BNE',
  'bruxelas': 'BRU',
  'bucareste': 'OPT',
  'budapeste': 'BUD',
  'buenos aires': 'EZE',
  'c do porto': 'OPO',
  'cairo': 'CAI',
  'campinas': 'VCP',
  'campo grande': 'CGR',
  'cancun': 'CUN',
  'caracas': 'CCS',
  'casablanca': 'CMN',
  'chicago': 'ORD',
  'cidade do cabo': 'CPT',
  'cidade do mexico': 'MEX',
  'ciudad del este': 'AGT',
  'copenhague': 'CPH',
  'cordoba': 'COR',
  'corumba': 'CMG',
  'cruzeiro do sul': 'CZS',
  'cuiaba': 'CGB',
  'curitiba': 'CWB',
  'cuzco': 'CUZ',
  'dacar': 'DKR',
  'dallas': 'DFW',
  'damasco': 'DAM',
  'denpasar': 'DPS',
  'denver': 'DEN',
  'detroit': 'DTW',
  'doha': 'DOH',
  'dortmund': 'DTM',
  'dubai': 'DXB',
  'dublin': 'DUB',
  'dusseldorf': 'DUS',
  'espargos': 'SID',
  'estocolmo': 'ARN',
  'florianopolis': 'FLN',
  'fort lauderdale': 'FLL',
  'fortaleza': 'FOR',
  'foz do iguacu': 'IGU',
  'frankfurt': 'FRA',
  'genebra': 'GVA',
  'goiania': 'GYN',
  'guadalajara': 'GDL',
  'guayaquil': 'GYE',
  'hamburg': 'HAM',
  'hannover': 'HAJ',
  'havana': 'HAV',
  'helsinque': 'HEL',
  'hong kong': 'HKG',
  'honolulu': 'HNL',
  'houston': 'IAH',
  'hulhule island': 'MLE',
  'istambul': 'IST',
  'jacarta': 'CGK',
  'jeddah': 'JED',
  'joao pessoa': 'JPA',
  'johannesburgo': 'JNB',
  'kiev': 'KBP',
  'kuala lumpur': 'KUL',
  'kuwait': 'KWI',
  'lagos': 'LOS',
  'las vegas': 'LAS',
  'lima': 'LIM',
  'lisboa': 'LIS',
  'londres': 'LHR',
  'londrina': 'LDB',
  'los angeles': 'LAX',
  'luanda': 'LAD',
  'macapa': 'MCP',
  'maceio': 'MCZ',
  'madri': 'MAD',
  'mahe': 'SEZ',
  'manaus': 'MAO',
  'manila': 'MNL',
  'maputo': 'MPM',
  'mascate': 'MCT',
  'melbourne': 'MEL',
  'miami': 'MIA',
  'milao': 'LIN',
  'montevideu': 'MVD',
  'montreal': 'YUL',
  'moscou': 'SVO',
  'mumbai': 'BOM',
  'munique': 'MUC',
  'nadi': 'NAN',
  'nagoya': 'NGO',
  'nairobi': 'NBO',
  'napoles': 'NAP',
  'nassau': 'NAS',
  'natal': 'NAT',
  'navegantes': 'NVT',
  'new york': 'JFK',
  'nova delhi': 'DEL',
  'nova iorque': 'JFK',
  'orlando': 'MCO',
  'osaka': 'KIX',
  'oslo': 'OSL',
  'ottawa': 'YOW',
  'panama city': 'PTY',
  'papeete': 'PPT',
  'paris': 'CDG',
  'pelotas': 'PET',
  'pequim': 'PEK',
  'perth': 'PER',
  'phuket': 'HKT',
  'ponta pora': 'PMG',
  'port louis': 'MRU',
  'porto alegre': 'POA',
  'porto velho': 'PVH',
  'praga': 'PRG',
  'providenciales': 'PLS',
  'puerto montt': 'PMC',
  'punta del este': 'PDP',
  'quebec': 'YQB',
  'quito': 'UIO',
  'recife': 'REC',
  'rio branco': 'RBR',
  'rio de janeiro': 'GIG',
  'riyadh': 'RUH',
  'roma': 'FCO',
  'rosario': 'ROS',
  'salvador': 'SSA',
  'san juan': 'SJU',
  'santiago': 'SCL',
  'sao francisco': 'SFO',
  'sao luis': 'SLZ',
  'sao paulo': 'GRU',
  'sao petersburgo': 'LED',
  'sarajevo': 'SJJ',
  'seattle': 'SEA',
  'seul': 'ICN',
  'shenzhen': 'SZX',
  'singapura': 'SIN',
  'sofia': 'SOF',
  'stuttgart': 'STR',
  'sydney': 'SYD',
  'taipei': 'TPE',
  'tampa': 'TPA',
  'tel aviv': 'TLV',
  'teresina': 'THE',
  'toquio': 'NRT',
  'toronto': 'YYZ',
  'uruguaiana': 'URG',
  'vancouver': 'YVR',
  'varsovia': 'WAW',
  'veneza': 'VCE',
  'viena': 'VIE',
  'vitoria': 'VIX',
  'washington': 'IAD',
  'washington d c': 'IAD',
  'washington dc': 'IAD',
  'wellington': 'WLG',
  'xangai': 'PVG',
  'zagreb': 'ZAG',
  'zurique': 'ZRH',
};

export function inferIataFromCity(city: string): string {
  const normalized = normalizeDestinationText(city).replace(/[^a-z0-9]+/g, ' ').trim();
  return IATA_BY_CITY[normalized] || '';
}
