import type { CanvasTheme } from './types';
import { MAV_LOGO_ASSET } from './assets';

export const CANVAS_THEMES: CanvasTheme[] = [
  {
    key: 'gomiles',
    name: 'Go Miles Club',
    fileSlug: 'gomilesclub',
    bg: '#FFFFFF',
    header: '#9935CB',
    headerTextColor: '#FFFFFF',
    headerStyle: 'pill',
    routeTitle: '#9935CB',
    separatorColor: '#02EEA0',
    separatorChar: '▸',
    miles: '#1F1033',
    dateLabel: '#9935CB',
    dateText: '#3A3A3A',
    divider: '#E3E6EC',
    footerBg: '#1F1033',
    footerText: '#FFFFFF',
    footerSub: '#C9BEDD',
    footerLogoMode: 'own',
    watermarkAsset: '/assets/logos/gomiles-light-tint.png',
    watermarkOpacity: 0.95,
    ownLogoAsset: '/assets/logos/gomiles.png',
    poweredLogoAsset: '/assets/logos/executiva-white.png',
    photoGradTop: '#B96FE0',
    photoGradBottom: '#9935CB',
    noPlane: true,
    photoBank: 'gomiles',
    frame: { inset: 36, radius: 28, outerBg: ['#2A1550', '#150A26'] }
  },
  {
    key: 'executiva',
    name: 'Executiva com Milhas',
    fileSlug: 'executivacommilhas',
    bg: '#FFFFFF',
    header: '#004AAD',
    routeTitle: '#004AAD',
    miles: '#2E2E2E',
    dateLabel: '#2E2E2E',
    dateText: '#2E2E2E',
    divider: '#E3E6EC',
    footerBg: '#004AAD',
    footerText: '#FFFFFF',
    footerSub: '#C9D6EC',
    footerLogoMode: 'own',
    hazard: ['#F2CB05', '#111111'],
    watermarkAsset: '/assets/logos/executiva-tint.png',
    watermarkOpacity: 0.13,
    ownLogoAsset: '/assets/logos/executiva-white.png',
    poweredLogoAsset: '/assets/logos/executiva-white.png',
    photoGradTop: '#B9D2F0',
    photoGradBottom: '#5C8FD6'
  },
  {
    key: 'firstclass',
    name: 'FirstClass',
    fileSlug: 'firstclass',
    bg: '#121E3E',
    header: '#F1C469',
    routeTitle: '#F1C469',
    miles: '#D1D3D9',
    dateLabel: '#D1D3D9',
    dateText: '#D1D3D9',
    divider: '#2C3A5E',
    footerBg: '#F1C469',
    footerText: '#121E3E',
    footerSub: '#4A4020',
    footerLogoMode: 'powered',
    hazard: ['#F1C469', '#121E3E'],
    watermarkAsset: '/assets/logos/firstclass.png',
    watermarkOpacity: 0.12,
    brandMarkAsset: '/assets/logos/firstclass.png',
    ownLogoAsset: '/assets/logos/gomiles.png',
    poweredLogoAsset: '/assets/logos/executiva-white.png',
    photoGradTop: '#2C3A5E',
    photoGradBottom: '#121E3E'
  },
  {
    key: 'milhasaovivo',
    name: 'Experiências Ao Vivo',
    fileSlug: 'milhasaovivo',
    bg: '#0E2038',
    header: '#F1C469',
    routeTitle: '#F1C469',
    miles: '#F1C469',
    dateLabel: '#F1C469',
    dateText: '#EFEAF5',
    divider: '#6FA0D8',
    footerBg: '#0E2038',
    footerText: '#EFEAF5',
    footerSub: '#F1C469',
    footerLogoMode: 'own',
    watermarkOpacity: 0.08,
    ownLogoAsset: MAV_LOGO_ASSET,
    poweredLogoAsset: '/assets/logos/executiva-white.png',
    photoGradTop: '#0E2038',
    photoGradBottom: '#060B14',
    noPlane: true
  }
];

export function getCanvasTheme(key: string): CanvasTheme {
  return CANVAS_THEMES.find((theme) => theme.key === key) ?? CANVAS_THEMES[0];
}
